import type { Application } from "express";
import { createVerifyJWT } from "../api/middleware/verifyJWT.js";
import { createVerifyStatusPageAccess } from "../api/middleware/verifyStatusPageAccess.js";
import { authApiLimiter } from "../api/middleware/rateLimiter.js";
import type { InitializedControllers } from "./controllers.js";
import type { ApiServices } from "@/config/services.api.js";

import { createAuthRoutes } from "@/api/routes/authRoutes.js";
import { createInviteRoutes } from "@/api/routes/inviteRoutes.js";
import { createMonitorRoutes } from "@/api/routes/monitorRoutes.js";
import { createCheckRoutes } from "@/api/routes/checkRoutes.js";
import { createGeoCheckRoutes } from "@/api/routes/geoCheckRoutes.js";
import { createSettingsRoutes } from "@/api/routes/settingsRoutes.js";
import { createMaintenanceWindowRoutes } from "@/api/routes/maintenanceWindowRoutes.js";
import { createQueueRoutes } from "@/api/routes/queueRoutes.js";
import { createLogRoutes } from "@/api/routes/logRoutes.js";
import { createStatusPageRoutes } from "@/api/routes/statusPageRoutes.js";
import { createDiagnosticRoutes } from "@/api/routes/diagnosticRoutes.js";
import { createNotificationRoutes } from "@/api/routes/notificationRoutes.js";
import { createTagRoutes } from "@/api/routes/tagRoutes.js";
import { createIncidentRoutes } from "@/api/routes/incidentRoutes.js";
import { createProxyRoutes } from "@/api/routes/proxyRoutes.js";
import { createEgressRoutes } from "@/api/routes/egressRoutes.js";

export const setupRoutes = (app: Application, controllers: InitializedControllers, apiServices: ApiServices) => {
	const verifyJWT = createVerifyJWT(apiServices.settingsService);
	const authRoutes = createAuthRoutes(controllers.authController, verifyJWT);
	const monitorRoutes = createMonitorRoutes(controllers.monitorController);
	const settingsRoutes = createSettingsRoutes(controllers.settingsController);
	const checkRoutes = createCheckRoutes(controllers.checkController);
	const geoCheckRoutes = createGeoCheckRoutes(controllers.geoCheckController);
	const inviteRoutes = createInviteRoutes(controllers.inviteController, verifyJWT);
	const maintenanceWindowRoutes = createMaintenanceWindowRoutes(controllers.maintenanceWindowController);
	const queueRoutes = createQueueRoutes(controllers.queueController);
	const logRoutes = createLogRoutes(controllers.logController);
	const verifyStatusPageAccess = createVerifyStatusPageAccess(apiServices.statusPagesRepository, verifyJWT);
	const statusPageRoutes = createStatusPageRoutes(controllers.statusPageController, verifyJWT, verifyStatusPageAccess);
	const notificationRoutes = createNotificationRoutes(controllers.notificationController);
	const tagRoutes = createTagRoutes(controllers.tagController);
	const diagnosticRoutes = createDiagnosticRoutes(controllers.diagnosticController, verifyJWT);
	const incidentRoutes = createIncidentRoutes(controllers.incidentController);
	const proxyRoutes = createProxyRoutes(controllers.proxyController);
	const egressRoutes = createEgressRoutes(controllers.egressController);

	app.use("/api/v1/auth", authApiLimiter, authRoutes);
	app.use("/api/v1/monitors", verifyJWT, monitorRoutes);
	app.use("/api/v1/settings", verifyJWT, settingsRoutes);
	app.use("/api/v1/checks", verifyJWT, checkRoutes);
	app.use("/api/v1/geo-checks", verifyJWT, geoCheckRoutes);
	app.use("/api/v1/invite", inviteRoutes);
	app.use("/api/v1/maintenance-window", verifyJWT, maintenanceWindowRoutes);
	app.use("/api/v1/queue", verifyJWT, queueRoutes);
	app.use("/api/v1/logs", verifyJWT, logRoutes);
	app.use("/api/v1/status-page", statusPageRoutes);
	app.use("/api/v1/notifications", verifyJWT, notificationRoutes);
	app.use("/api/v1/tags", verifyJWT, tagRoutes);
	app.use("/api/v1/diagnostic", verifyJWT, diagnosticRoutes);
	app.use("/api/v1/incidents", verifyJWT, incidentRoutes);
	app.use("/api/v1/proxies", verifyJWT, proxyRoutes);
	app.use("/api/v1/egress", verifyJWT, egressRoutes);
};
